name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]
    paths:
      - "runner-images/*Dockerfile"

jobs:
  push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # required for ghcr.io

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: runner-images/import-package.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}/import-package:latest