name: Update Debian Repository

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: read # required for ghcr.io

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/import-package:latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: packages

      - name: Generate GitHub App token for accessing 
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.PACKAGES_ACCESS_APP_ID }}
          private-key: ${{ secrets.PACKAGES_ACCESS_PRIVATE_KEY }}
          owner: sleiphan
          repositories: |
            ctools
            blackhole-session-provider

      - name: Fix workspace permissions
        run: |
          chown -R $(id -u):$(id -g) .

      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Download latest release from projects
        shell: bash
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          mkdir -p incoming

          repos=(
            sleiphan/ctools
            sleiphan/blackhole-session-provider
          )

          for repo in "${repos[@]}"; do
            gh release download \
              --repo $repo \
              --pattern "*.deb" \
              --dir incoming/
          done

      - name: Include package in repo
        run: |
          reprepro includedeb stable incoming/*.deb
      
      - name: Remove files that should not be added to the repo.
        run: |
          rm -rf incoming

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update repo"
          git push
